# .github/workflows/cloud-run-deploy.yml

name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main  # Adjust the branch as needed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v3

      # Setup gcloud CLI
      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ankercloud-testing-account
          export_default_credentials: true

      # Configure Docker to use gcloud as a credential helper
      - name: Configure Docker authentication
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      # Build the Docker image
      - name: Build Docker Image
        run: |
          docker build -t us-central1-docker.pkg.dev/ankercloud-testing-account/gen-ai-poc/php-app .

      # Push the Docker image to Artifact Registry
      - name: Push Docker Image to Artifact Registry
        run: |
          docker push us-central1-docker.pkg.dev/ankercloud-testing-account/gen-ai-poc/php-app

      # Deploy the Docker image to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy php-app \
            --service-account 263666966446-compute@developer.gserviceaccount.com \
            --allow-unauthenticated \
            --memory 1024Mi \
            --platform managed \
            --image us-central1-docker.pkg.dev/ankercloud-testing-account/gen-ai-poc/php-app:latest \
            --timeout 30 \
            --min-instances 0 \
            --max-instances 1 \
            --ingress all \
            --region us-central1
